# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_info.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Informacion(object):
    def setupUi(self, Informacion):
        Informacion.setObjectName(_fromUtf8("Informacion"))
        Informacion.resize(261, 264)
        self.gridLayout = QtGui.QGridLayout(Informacion)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.nombre = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.nombre.setFont(font)
        self.nombre.setText(_fromUtf8(""))
        self.nombre.setObjectName(_fromUtf8("nombre"))
        self.verticalLayout.addWidget(self.nombre)
        self.raza = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.raza.setFont(font)
        self.raza.setText(_fromUtf8(""))
        self.raza.setObjectName(_fromUtf8("raza"))
        self.verticalLayout.addWidget(self.raza)
        self.especie = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.especie.setFont(font)
        self.especie.setText(_fromUtf8(""))
        self.especie.setObjectName(_fromUtf8("especie"))
        self.verticalLayout.addWidget(self.especie)
        self.color = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.color.setFont(font)
        self.color.setText(_fromUtf8(""))
        self.color.setObjectName(_fromUtf8("color"))
        self.verticalLayout.addWidget(self.color)
        self.sexo = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.sexo.setFont(font)
        self.sexo.setText(_fromUtf8(""))
        self.sexo.setObjectName(_fromUtf8("sexo"))
        self.verticalLayout.addWidget(self.sexo)
        self.peso = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.peso.setFont(font)
        self.peso.setText(_fromUtf8(""))
        self.peso.setObjectName(_fromUtf8("peso"))
        self.verticalLayout.addWidget(self.peso)
        self.edad = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.edad.setFont(font)
        self.edad.setText(_fromUtf8(""))
        self.edad.setObjectName(_fromUtf8("edad"))
        self.verticalLayout.addWidget(self.edad)
        self.nacimiento = QtGui.QLabel(Informacion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.nacimiento.setFont(font)
        self.nacimiento.setText(_fromUtf8(""))
        self.nacimiento.setObjectName(_fromUtf8("nacimiento"))
        self.verticalLayout.addWidget(self.nacimiento)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Informacion)
        QtCore.QMetaObject.connectSlotsByName(Informacion)

    def retranslateUi(self, Informacion):
        Informacion.setWindowTitle(_translate("Informacion", "Información", None))
        self.label.setText(_translate("Informacion", "Nombre", None))
        self.label_2.setText(_translate("Informacion", "Raza", None))
        self.label_3.setText(_translate("Informacion", "Especie", None))
        self.label_4.setText(_translate("Informacion", "Color", None))
        self.label_5.setText(_translate("Informacion", "Sexo", None))
        self.label_6.setText(_translate("Informacion", "Peso", None))
        self.label_7.setText(_translate("Informacion", "Edad", None))
        self.label_8.setText(_translate("Informacion", "Nacimiento", None))

