# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_registro.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RegistroMascota(object):
    def setupUi(self, RegistroMascota):
        RegistroMascota.setObjectName(_fromUtf8("RegistroMascota"))
        RegistroMascota.resize(442, 219)
        self.gridLayout = QtGui.QGridLayout(RegistroMascota)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.nombreEdit = QtGui.QLineEdit(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.nombreEdit.setFont(font)
        self.nombreEdit.setObjectName(_fromUtf8("nombreEdit"))
        self.horizontalLayout_2.addWidget(self.nombreEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.sexoEdit = QtGui.QLineEdit(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.sexoEdit.setFont(font)
        self.sexoEdit.setObjectName(_fromUtf8("sexoEdit"))
        self.horizontalLayout_3.addWidget(self.sexoEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.razaEdit = QtGui.QLineEdit(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.razaEdit.setFont(font)
        self.razaEdit.setObjectName(_fromUtf8("razaEdit"))
        self.horizontalLayout_4.addWidget(self.razaEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.colorEdit = QtGui.QLineEdit(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.colorEdit.setFont(font)
        self.colorEdit.setObjectName(_fromUtf8("colorEdit"))
        self.horizontalLayout_5.addWidget(self.colorEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.especieEdit = QtGui.QLineEdit(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.especieEdit.setFont(font)
        self.especieEdit.setObjectName(_fromUtf8("especieEdit"))
        self.horizontalLayout.addWidget(self.especieEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.fechaEdit = QtGui.QDateEdit(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.fechaEdit.setFont(font)
        self.fechaEdit.setDate(QtCore.QDate(2016, 1, 3))
        self.fechaEdit.setCalendarPopup(True)
        self.fechaEdit.setObjectName(_fromUtf8("fechaEdit"))
        self.horizontalLayout_6.addWidget(self.fechaEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.pesoEdit = QtGui.QLineEdit(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.pesoEdit.setFont(font)
        self.pesoEdit.setText(_fromUtf8(""))
        self.pesoEdit.setObjectName(_fromUtf8("pesoEdit"))
        self.horizontalLayout_7.addWidget(self.pesoEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(RegistroMascota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 2)

        self.retranslateUi(RegistroMascota)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RegistroMascota.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RegistroMascota.reject)
        QtCore.QMetaObject.connectSlotsByName(RegistroMascota)

    def retranslateUi(self, RegistroMascota):
        RegistroMascota.setWindowTitle(_translate("RegistroMascota", "Registro de Mascota", None))
        self.label.setText(_translate("RegistroMascota", "Nombre", None))
        self.label_3.setText(_translate("RegistroMascota", "Sexo", None))
        self.label_5.setText(_translate("RegistroMascota", "Raza", None))
        self.label_7.setText(_translate("RegistroMascota", "Color", None))
        self.label_2.setText(_translate("RegistroMascota", "Especie", None))
        self.label_4.setText(_translate("RegistroMascota", "Nacimiento", None))
        self.label_6.setText(_translate("RegistroMascota", "Peso", None))

